### ISSUE TITLE
https://pypi.python.org/pypi

### ISSUE THREAD

**Issue by region51** [barrust/Wikipedia#3]
_@barrust hi, https://github.com/goldsmith/Wikipedia dead two years._
_Please, add your new Wikipedia on https://pypi.python.org/pypi._
_P.S. Sorry for my bad English._

**Comment by region51** [comment]
@barrust tag question???

**Comment by barrust** [comment]
I am just setting this as a request and not as a bug (for personal tracking purposes). Getting it onto PyPi is a goal of mine. So I hope I will be able to push it in the coming days. Getting the documentation hosted somewhere is also on the plan.

**Comment by region51** [comment]
>Getting it onto PyPi is a goal of mine. So I hope I will be able to push it in the coming days.

This Is very good news.

**Comment by nikicc** [comment]
Any progress on this?

**Comment by barrust** [comment]
Not yet. I am still looking into what I would need to do to get it pushed to pypi.

**Comment by barrust** [comment]
@region51 and @nikicc:

I have decided that to better support my requirements, which includes the ability to change MediaWiki sites, I needed to re-write the library with that in mind. The result is [pymediawiki](https://github.com/barrust/mediawiki) which has been uploaded to PyPi. 

To install you can run the following: 
``` bash
pip install pymediawiki
```

The default MediaWiki site is Wikipedia but the syntax is slightly different. To get basic Wikipedia data,  one would only need to do the following:

``` python
import mediawiki

wikipedia = MediaWiki()
star_wars = wikipedia.page('Star Wars')
```

I have almost completed porting all functionality. Please report any issues with pymediawiki in the [issue tracker](https://github.com/barrust/mediawiki/issues).

I have also uploaded the [full documentation](http://pythonhosted.org/pymediawiki/)

I will, therefore, not be maintaining this fork any longer as the original author has started to update the [original code](https://github.com/goldsmith/Wikipedia).

Thanks!

**Comment by nikicc** [comment]
@barrust thanks for the update 👍  Will look into pymediawiki.
